version: "3"

services:
  blockscout-l2:
    image: metis/blockscout
    # depends_on:
    #   - postgres
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    expose:
      - 4000
    ports:
      - 80:4000
    env_file:
      - envs/l2-488.env
    environment:
            #- DATABASE_URL=postgresql://postgres:postgres@192.168.31.146:5432/blockscout-l2?ssl=false
      - DATABASE_URL=postgresql://admin:admin12345@172.31.93.190:5432/blockscouttest
    command: mix phx.server
