version: "3"

services:
  blockscout-l2:
    image: metis/blockscout
    # depends_on:
    #   - postgres
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    expose:
      - 80
    ports:
      - 80:80
    env_file:
      - envs/l2-488.env
    environment:
      - DATABASE_URL=postgresql://blockscout_app:rEuA9mAU@34.237.142.214:5432/blockscout
    command: mix phx.server
