name: Deploy to test

on:
  push:
    branches: stackexpress-test

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest


    steps:
    - name: Check out code
      uses: actions/checkout@v2



    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, tag, and push image to Amazon ECR
      id: build-image

      run: |
        echo "Building image for explorer"
        ls -la && pwd
        docker-compose -f  ./docker/docker-compose-l2-blockscout.yml build -t blockscout-test .

        echo "Adding tag"

        docker tag blockscout-test:latest 950087689901.dkr.ecr.us-east-1.amazonaws.com/blockscout-test:latest

        echo "pushing the build to ecr repo"

        docker push 950087689901.dkr.ecr.us-east-1.amazonaws.com/blockscout-test:latest

        echo "runing migrate"

        docker-compose -f ./docker/docker-compose-l2-migrate.yml up
